Creating Payment Methods for Future Purchases
hatchways/team-cedar pull request #113
Opened 2022-02-02 14:32 UTC by RetiFier

### What this PR does (required):
- Can Save and Retrieve Payment Methods for Future Purchases from stripe

### Screenshots / Videos (front-end only):
![image](https://user-images.githubusercontent.com/50056219/152172768-fa49279b-037c-4758-908e-69361e828e7f.png)
![image](https://user-images.githubusercontent.com/50056219/152172824-71e80a5a-950b-4f58-80e0-25ca17a4c62a.png)

### Any information needed to test this feature (required):
- In Setting Payments Methods can add New Payments Methods. 
- After Adding the Payments, the saved payments will show 
-  http://localhost:3001/payment_methods/session POST to create new payments methods 
- http://localhost:3001/payment_methods/session GET to get the saved payments methods

### Any issues with the current functionality (optional):
- This Branch is branch from stripe-connect branch
- The Stripe Connect Component will works after adding role base nav bar.

2022-02-02 21:38 UTC, ezeilo-su requested changes
Hey @RetiFier, good work on this one. Please take al look at those comments and address them.

2022-02-02 21:38 UTC, ezeilo-su commented on client/src/pages/Settings/Settings.tsx
> +  // },
Please move unused code away from here

2022-02-02 21:38 UTC, ezeilo-su commented on server/controllers/paymentMethod.js
> +// @access Private
Good documentation

2022-02-02 21:38 UTC, ezeilo-su commented on server/controllers/paymentMethod.js
> +  console.log(getProfile?.stripeCustomerId);
Please watch for unnecessary logs to the console. Going forward, we should be cleaning up our logs done during development. Thanks!

2022-02-02 21:38 UTC, ezeilo-su commented on server/controllers/stripe.js
> +      console.log(error);
You can use `console.error` for this one

2022-02-04 16:38 UTC, moffatethan approved these changes

2022-02-04 17:02 UTC, merged