Creating a UI for Manage Bookings
hatchways/team-cedar pull request #67
Opened 2022-01-15 21:46 UTC by RetiFier

### What this PR does (required):
- Calendar Functionality
- Upcoming Booking UI
### Screenshots / Videos (front-end only):
![image](https://user-images.githubusercontent.com/50056219/149638573-752a816c-0f4e-42ea-bdeb-fb00b8e5890b.png)
![image](https://user-images.githubusercontent.com/50056219/149638583-b04c19cf-e404-4529-8f5c-6ff5058e668d.png)

### Any information needed to test this feature (required):
- Checking the Current Date in Calendar
- Selecting the Dates in Calendar

2022-01-16 20:27 UTC, ezeilo-su requested changes
Good work on this one. Just a few comments, though. Also, note that you should always link your ticket to your PRs.

2022-01-16 20:27 UTC, sundayezeilo commented on client/src/components/BookingContent/BookingContent.tsx
> +          {accept ? 'ACCEPTED' : 'DECLINED'}
Please avoid using CAPITALCASE for text, some screen readers interpret this text as abbreviations, you can resort to using a CSS class to transform text instead.

2022-01-16 20:27 UTC, sundayezeilo commented on client/src/components/CalendarDates/CalendarDates.tsx
> +    //To Terminate the loop
You can remove this comment since it's not needed here

2022-01-16 20:27 UTC, ezeilo-su commented on client/src/pages/ManageBooking/ManageBooking.tsx
> +    // loading for a split seconds until history.push works
Remove comment, please

2022-01-17 15:51 UTC, ezeilo-su reviewed
Thank you for making the requested changes

2022-01-17 15:51 UTC, ezeilo-su commented on client/src/components/BookingContent/BookingContent.tsx
> +          {accept ? 'accepted' : 'declined'}
:+1:

2022-01-18 15:16 UTC, moffatethan commented
Quick comment before going into my review, looks a bit odd on smaller screens. For this page, we can stack the UI early on - I'm fine with that.

![image](https://user-images.githubusercontent.com/38387163/149964730-f1e4006b-c555-40cf-83eb-74b51f6ed0fc.png)

2022-01-18 15:25 UTC, moffatethan requested changes
Just a minor comment, interesting approach you did for the calendar. I'm not against it, I think it works for our purpose but would like to see more responsiveness from it.

2022-01-18 15:25 UTC, moffatethan commented on client/src/components/BookingWrapper/BookingWrapper.tsx
> +        padding: { xs: 2, md: 3, lg: 3 },
💯

2022-01-18 15:25 UTC, moffatethan commented on client/src/components/NextBooking/NextBooking.tsx
> +  };
Just for integration, we should ideally be passing this via props

2022-01-20 20:11 UTC, moffatethan approved these changes
Good work

2022-01-20 20:14 UTC, merged