Create profile details page
hatchways/team-cedar pull request #93
Opened 2022-01-20 17:55 UTC by Abhi-S-1

### What this PR does (required):
- A profile page that shows a person's details. Design based on the pet sitter demo video.

### Screenshots / Videos (front-end only):
!["Screenshot of the profile details page"](https://raw.githubusercontent.com/hatchways/team-cedar/profileDetailsPage/demo/images/profiledetails.png)

### Any information needed to test this feature (required):
- Simply run the app and visit /profile/details

### Any issues with the current functionality (optional):
- There is no check to see which user it is. Right now it's just a general page with a hard coded profile object
- None of the buttons do anything currently

2022-01-20 21:13 UTC, ezeilo-su commented
Please resolve the merge conflict before your PR can receive a review.

2022-01-20 21:55 UTC, Abhi-S-1 commented
> Please resolve the merge conflict before your PR can receive a review.

The merge conflict is now resolved

2022-01-21 00:09 UTC, moffatethan requested changes
Just some comments to use Formik and layout clean up. Not set on this UI right now, the layout is good but just each column seems to be odd design so we'll perfect it as we go but for now this is a good start.

2022-01-21 00:09 UTC, moffatethan commented on client/src/App.tsx
> +                <Route exact path="/profile/details" component={ProfileDetails} />
Wouldn't we need to pass in the profile id of the user we are trying to see? Of course static for now, can still be passed in though.

2022-01-21 00:09 UTC, moffatethan commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +  const [value, setValue] = React.useState<number | null>(0);
Let's use Formik here instead of state, will make things really easy for us. 🙂

2022-01-21 00:09 UTC, moffatethan commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +  };
These can all be removed when you setup Formik 👍🏻

2022-01-21 00:09 UTC, moffatethan commented on client/src/pages/ProfileDetails/ProfileDetails.tsx
> +          </Grid>
Let's remove this. I don't see the need to have the rating on the booking card (sorry if I said to put it here), rather let's put a card underneath the booking request to submit a rating.

2022-01-24 19:03 UTC, Abhi-S-1 commented
Updates made!

2022-02-01 03:48 UTC, moffatethan approved these changes
@RetiFier Can we merge this in

2022-02-02 20:05 UTC, merged