Navbar conditional rendering
hatchways/team-cedar pull request #95
Opened 2022-01-21 17:43 UTC by Abhi-S-1

### What this PR does (required):
- Makes it so that certain links in the navbar are viewed only based on your account type.

### Screenshots / Videos (front-end only):
!["navbar pet owner"](https://raw.githubusercontent.com/hatchways/team-cedar/navbarConditionalRendering/demo/images/navbar1.png)

!["navbar pet sitter"](https://raw.githubusercontent.com/hatchways/team-cedar/navbarConditionalRendering/demo/images/navbar2.png)

!["navbar logged out"](https://raw.githubusercontent.com/hatchways/team-cedar/navbarConditionalRendering/demo/images/navbar3.png)

### Any information needed to test this feature (required):
- Must have a profile in mongodb with accountType as either pet_owner or pet_sitter. Switch between both, as well as logging out on the app to see the three different navbar states

### Any issues with the current functionality (optional):

2022-01-21 17:45 UTC, Abhi-S-1 commented
Wasn't sure if this is how you wanted the task to be complete and also wasn't sure about best practices. Therefore, let me know if you want anything changed!

2022-02-01 03:51 UTC, moffatethan requested changes

2022-02-01 03:51 UTC, moffatethan commented on client/src/components/Navbar/Navbar.tsx
> +          if (!menu.canView || menu.canView == profile.accountType || menu.canView.length > 1) {
Not quite the approach that was expected. If the account type is included in the canView list then render the route.

2022-02-01 03:51 UTC, moffatethan commented on server/models/User.js
> +  },
Now that we have separated let's keep this out

2022-02-04 15:45 UTC, moffatethan requested changes
Please address merge conflicts

2022-02-04 16:04 UTC, RetiFier commented
> Please address merge conflicts

@moffatethan Merge Conflicts has been resolved

2022-02-04 16:42 UTC, moffatethan approved these changes

2022-02-04 17:03 UTC, merged