Add Payment Controller and Payment Route
hatchways/team-cedar pull request #97
Opened 2022-01-24 21:45 UTC by RetiFier

### What this PR does (required):
- Get Request for all payment and single payment
- Put Request for make payment and cancel payment

### Any information needed to test this feature (required):
- Need to add data manually 
- http://localhost:3001/payments for Get All Payments
- http://localhost:3001/payments/:id Get single Payments
- http://localhost:3001/payments/:id/pay Make Payment with Put Method
- http://localhost:3001/payments/:Id/cancel Cancel Payment with Put Method
- Merchant user can only cancel

2022-01-25 21:52 UTC, ezeilo-su requested changes
This is cool. Just a few comment to have a look

2022-01-25 21:52 UTC, ezeilo-su commented on server/controllers/payment.js
> +    res.status(203);
I think this should be a 401 ("Unauthorized") status

2022-01-25 21:52 UTC, ezeilo-su commented on server/controllers/payment.js
> +if(payment){
There's no need for this check as this query will always return an array, which is always truthy, even when it's an empty array.

2022-01-25 23:19 UTC, moffatethan requested changes
Just some changes to do, overall decent work.

2022-01-25 23:19 UTC, moffatethan commented on server/controllers/payment.js
> +  const {id} = req.params;
```suggestion
  const { id } = req.params;
```

2022-01-25 23:19 UTC, moffatethan commented on server/controllers/payment.js
> +  }
Could we add some whitespace above this conditional. Also, Could we do a different approach.

```js
if (!payment) {
   . . .
}

return res.status(200).json({  . . . });
```

2022-01-25 23:19 UTC, moffatethan commented on server/controllers/payment.js
> +  }
Ditto throughout the controller

2022-01-25 23:19 UTC, moffatethan commented on server/controllers/payment.js
> +    throw new Error("Only Merchant Can Cancle");
```suggestion
    throw new Error("Only merchant can cancel");
```

2022-01-25 23:19 UTC, moffatethan commented on server/controllers/payment.js
> +    merchantPayment.set(({paid: false}))
Can we do a quick schema change and add a cancel boolean to the payment and set that to true so we can filter that out on our queries. 🤔

2022-01-25 23:19 UTC, moffatethan commented on server/routes/payment.js
> +router.route("/").get(protect, getAllPayments);
We need a post to create a payment too 👍🏻

2022-02-01 03:51 UTC, moffatethan requested changes
Address merge conflicts please

2022-02-01 10:19 UTC, RetiFier commented
> Address merge conflicts please

@moffatethan  Resolved Conflicts

2022-02-04 15:46 UTC, moffatethan requested changes
Please address merge conflicts

2022-02-04 16:30 UTC, moffatethan approved these changes

2022-02-04 17:00 UTC, merged