Integrate Manage Bookings UI
hatchways/team-cedar pull request #98
Opened 2022-01-25 23:41 UTC by RetiFier

### What this PR does (required):
- Integrate Manage Bookings UI and Request Controller

### Screenshots / Videos (front-end only):
![image](https://user-images.githubusercontent.com/50056219/151077018-875ddc51-9103-4ea5-8894-58e318df4eea.png)
![image](https://user-images.githubusercontent.com/50056219/151077051-26a368af-9c9d-4371-8107-adf111b549d6.png)
![image](https://user-images.githubusercontent.com/50056219/151077065-121d8988-7445-4dfb-802b-4432f03bb5eb.png)

### Any information needed to test this feature (required):
- Next Booking Should be display when accept and decline are false
- Current Booking Should be display when accepted and the data are sort with latest updated
- Past Booking are the accepted booking that expire 

### Any issues with the current functionality (optional):
- Request Data need to be create manually

2022-01-26 17:19 UTC, ezeilo-su reviewed
Good work with this one!

2022-02-01 03:51 UTC, moffatethan requested changes
Address merge conflicts please

2022-02-01 10:26 UTC, RetiFier commented
> Address merge conflicts please

@moffatethan Resolved Merge Conflicts

2022-02-04 15:46 UTC, moffatethan approved these changes

2022-02-04 16:06 UTC, merged