Make Searching functional based on city
hatchways/team-cedar pull request #99
Opened 2022-01-28 11:38 UTC by RetiFier

### What this PR does (required):
- Create Pet Sitter Controller 
- Make Searching functional based on city

### Screenshots / Videos (front-end only):
![image](https://user-images.githubusercontent.com/50056219/151539478-4c53b5bb-42ee-45e1-8e4f-4a024a3358d0.png)
![image](https://user-images.githubusercontent.com/50056219/151539510-97b7e3ba-db64-4a9c-982a-6ecd65dd4e94.png)

### Any information needed to test this feature (required):
- http://localhost:3001/petsitter for create petsitters and get petsitters
- http://localhost:3001/petsitter?address=city to search petsitter by city
- http://localhost:3001/petsitter/:id/edit to edit petsitters data such as rate, availability
- Should display search results in the user interface

### Any issues with the current functionality (optional):
- The availability search is not yet complete due to the development of the availability controller.
- The schedule base search is already implemented in the backend, but it needs to be fixed depending on availability.

2022-01-28 13:01 UTC, ezeilo-su requested changes
Good progress on this one, @RetiFier. I left you a few comments to address.
Happy coding!

2022-01-28 13:01 UTC, sundayezeilo commented on server/controllers/petSitter.js
> +// @access private
Nice documentation

2022-01-28 13:01 UTC, sundayezeilo commented on server/controllers/petSitter.js
> +// @access Private
:+1:

2022-01-28 13:01 UTC, sundayezeilo commented on server/controllers/petSitter.js
> +    const updatedPetSitter = await petSitter.save();
This approach would set any specified field that did not exist in the request body to `undefined`. You can simply use mongoose `findOneAndUpdate` to update your document.

2022-01-28 13:01 UTC, ezeilo-su commented on server/routes/petSitter.js
> +router.route("/:id/edit").put(protect, updatePetSitterById);
Use a `PATCH` request here if you're not updating the whole resource

2022-02-04 15:49 UTC, moffatethan requested changes
Please address merge conflicts

2022-02-04 16:31 UTC, moffatethan approved these changes

2022-02-04 17:00 UTC, merged